version: "3.3"

services:
  nginx:
    image: jwilder/nginx-proxy
    networks:
      - internal
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    #  - "./certs:/etc/nginx/certs"
    ports:
      - "80:80"
    #  - "443:443"

  # traefik:
  #   image: traefik
  #   command:
  #     - "--accessLog=true"
  #     - "--entrypoints.web.address=:80"
  #     - "--api.dashboard=true"
  #     - "--providers.docker.endpoint=unix:///var/run/docker.sock"
  #     - "--providers.docker.exposedByDefault=false"
  #     - "--providers.docker.network=internal"
  #   networks:
  #     - internal
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #   ports:
  #     - "80:80"
  #   deploy:
  #     placement:
  #       constraints:
  #         - "node.role==manager"

  mongodb:
    image: mongo
    networks:
      - internal
    volumes:
      - "./mongodb:/data/db"
    ports:
      - "27017:27017"

  registry:
    image: verdaccio/verdaccio
    networks:
      - internal
    volumes:
      - "./registry:/verdaccio/conf"
    ports:
      - "4873:4873"

  catalogue:
    image: catalogue
    build: "./catalogue"
    networks:
      - internal
    ports:
      - "80:3000"
    depends_on:
      - registry
    environment:
      - "VIRTUAL_HOST=catalogue.docker-pi.local"
      - "ROOT_DOMAIN=docker-pi.local"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.manager.rule=HOST(`catalogue.docker-pi.local`)"
      - "traefik.http.services.manager.loadbalancer.server.port=80"
      - "traefik.http.routers.manager.entrypoints=web"

  manager:
    image: manager
    build: "./manager"
    depends_on:
      - mongodb
    networks:
      - internal
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    environment:
      - "VIRTUAL_HOST=manager.docker-pi.local"
      - "MONGO_URL=mongodb://mongodb/nodered"
      - "ROOT_DOMAIN=docker-pi.local"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.manager.rule=HOST(`manager.docker-pi.local`)"
      - "traefik.http.services.manager.loadbalancer.server.port=3000"
      - "traefik.http.routers.manager.entrypoints=web"


networks:
  internal:
    external:
      name: "internal"
